product = input()
price = int(input())
weight = int(input())
amount = int(input())
print('================Чек================')
print(f"Товар: {product}")
print(f"Цена: {weight}кг * {price}руб/кг")
print(f"Итого: {price*weight}руб")
print(f"Внесено: {amount}руб")
print(f"Сдача: {amount-price*weight}руб")
print('===================================')